import { Geist, Geist_Mono, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// বাংলা ফন্ট 
const hindSiliguri = Hind_Siliguri({
  weight: ['300', '400', '500', '600', '700'],
  variable: "--font-hind-siliguri",
  subsets: ["bengali"],
});

export const metadata = {
  title: "Foodduniya",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="bn">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.variable} antialiased`}
      >
        <Navbar/>
        {children}

        <Footer/>
        <ToastContainer
          autoClose={2000}
          hideProgressBar={true}
          closeOnClick
          pauseOnHover
          draggable={true}
          position="top-right"
          toastClassName=""
          bodyClassName=""
          progressClassName=""
          pauseOnFocusLoss={true}
          newestOnTop={true}
          theme="colored"
        />
      </body>
    </html>
  );
}